Fix/tracing plugin
stack-spot/graphene-java-api-stack pull request #10
Opened 2022-09-14 16:13 UTC by lucas-almeida-zup

- added global inputs
- added maven build tool support

2022-09-15 03:39 UTC, dearrudam requested changes

2022-09-15 03:39 UTC, dearrudam commented on tracing-plugin/plugin.yaml
> +    indent: "    "
@lucas-almeida-zup em meus testes locais, comentei esse linha o atributo `indent` e a identação do arquivo foi respeitada pelo hook então acredito que não há necessidade de informar esse atributo `indent`. IMHO, isto é, talvez eu esteja equivocado, mas se não tiver, talvez seja uma boa remover a definição desse atributo para evitar criar confusão para quem for utilizar essa definição como exemplo.

2022-09-15 13:11 UTC, wesleyzup requested changes

2022-09-15 13:56 UTC, lucas-almeida-zup commented on tracing-plugin/plugin.yaml
> +    indent: "    "
@dearrudam Ele mantém '\t' como padrão, mas o padrão utilizado são 4 espaços por isso coloquei esse valor pra não alterar muito o arquivo padrão pom gerado pelo template

2022-09-15 13:57 UTC, lucas-almeida-zup commented on tracing-plugin/plugin.yaml
> +    indent: "    "
Boa, realmente com inteiros fica melhor, vou fazer a alteração

2022-09-15 13:58 UTC, lucas-almeida-zup commented on tracing-plugin/plugin.yaml
> +#          Add in future version of CLI
Pelo que entendi é apenas para o tipo 'edit' o 'edit-xml' ainda não possui essa funcionalidade, certo?

2022-09-15 14:03 UTC, dearrudam commented on tracing-plugin/plugin.yaml
> +    indent: "    "
@lucas-almeida-zup Okay :+1:, nos meus testes não mudou nada na indentação, mas sabemos que o xml em si isso não é um problema ou algo muito importante pois o desenvolvedor pode reformatar o xml na IDE dele e quebrar essa indentação, não é? Mas por mim está okay :wink: !

2022-09-15 14:52 UTC, lucas-almeida-zup commented on tracing-plugin/plugin.yaml
> +    indent: "    "
Confirmei com testes e não é possível, o link que você passou é 'edit-yaml' mas o utilizado é 'edit-xml'

2022-09-23 18:56 UTC, wesleyzup approved these changes

2022-09-26 13:28 UTC, merged