Criação de plugin para suporte de banco de dados relacional - versão inicial
stack-spot/graphene-java-api-stack pull request #13
Opened 2022-09-25 18:42 UTC by vitorbg

Nesta primeira versão o plugin "db-relation-plugin" acrescenta a opção de adicionar ao docker-compose.yaml do projeto o suporte para banco de dados relacional (PostgreSQL ou MariaDB).

2022-09-26 16:55 UTC, wesleyzup requested changes
Vitor, muito obrigado pelo sua contribuição.
Fiz algumas solicitações para que possam ser ajustadas. 

Segue outras considerações:
É importante que adicionar um plugin de banco de dados, a dependencia do mesmo seja adicionada no arquivo gradle ou maven de acordo com a escolha do usuário. 

Acredito que para esse plugin faça sentido perguntar se o usuário gostaria de utilizar o JDBC template, JDBC puro ou spring data, e assim o plugin criar estrutura como exemplo, configurada e integrada com o banco de dados, seguindo os padrões da abordagem conforme a escolha. 

Faz sentido para o contexto?

2022-09-26 16:55 UTC, wesleyzup commented on db-relational-plugin/snippets/mariadb.yaml
> +networks:
Olá Vitor, boa tarde. 
Segue alguns pontos para serem ajustados:

- Utilizar o network já presente no docker-compose 

```
networks:
  app-meuap:
    driver: bridge
```

- Remover o valor **null** do volume criado para o database escolhido.

- Adicionar propriedade depends-on no serviço da  aplicação, pois em alguns casos futuros ela pode precisar que o do banco de dados esteja disponível para que seja iniciada. Ex:
```
    depends_on:
      - <mariadb ou postgresql>-server
```

2022-09-27 20:47 UTC, vitorbg commented
> Faz sentido sim. Como são 3 opções e considerando próximos passos de compatibilidade com Maven e Gradle, vejo como prioridade a utilização inicialmente com Spring Data, e, realizar incremento com as opções de JDBC Template e JDBC puro.

2022-10-05 21:00 UTC, lucas-almeida-zup reviewed
Por favor revisar comentários

2022-10-05 21:00 UTC, lucas-almeida-zup commented on db-relational-plugin/snippets/postgresql/gradle-dependencies.txt
> +    testImplementation group: 'org.testcontainers', name: 'postgresql', version: '1.17.3'
Mesmo comentário de: `db-relational-plugin/snippets/mariadb/maven-dependencies.xml`

2022-10-10 14:28 UTC, vitorbg commented on db-relational-plugin/docs/usage.md
> +É possível aplicar este Plugin em uma aplicação do tipo APP utilizando a linha de comando da Stackspot (STK CLI). Para isso, basta executar o seguinte comando:
Belezura. Eu ajustei todas as docs do plugin :)
Obrigado pela pontuação.

2022-10-10 14:29 UTC, vitorbg commented on db-relational-plugin/docs/use-case.md
> +# Usecase
Belezura. Eu ajustei todas as docs do plugin :)
Obrigado pela pontuação.

2022-10-10 14:34 UTC, vitorbg commented on db-relational-plugin/snippets/mariadb/application-test.yaml
> +  datasource:
Isso mesmo. Este trecho é considerado no escopo de execução dos testes unitários.

2022-10-10 14:36 UTC, vitorbg commented on db-relational-plugin/snippets/mariadb/maven-dependencies.xml
> +</dependency>
Nesta primeira versão, estou considerando que o plugin será aplicado a projetos que foram criados pelo graphene.
Para evoluções do plugin e deixa-lo aplicavel em qualquer projeto é necessário:
-> Verificar build tool
-> Verificar se as dependencias existem
-> Verificar se o projeto possui application.yaml ou application.properties
Acredito que podemos abrir uma issue para tratar este ponto, e, deixar no radar né?

2022-10-10 14:39 UTC, vitorbg commented on db-relational-plugin/snippets/postgresql/application.yaml
> +    password: postgres
A principio, deixei um trecho na documentação orientando a usar variável de ambiente para o ambiente produtivo.
Acredito que podemos abrir uma issue com os seguintes pontos:
-> Colocar variável de ambiente via docker, e, ajustar o Dockerfile.
ou
-> Criar trecho de código que faz a leitura de um arquivo txt para ler usuario/senha do banco de dados, simulando uma secret do kubernetes.

2022-10-10 14:39 UTC, vitorbg commented on db-relational-plugin/snippets/postgresql/maven-dependencies.xml
> +</dependency>
Nesta primeira versão, estou considerando que o plugin será aplicado a projetos que foram criados pelo graphene.
Para evoluções do plugin e deixa-lo aplicavel em qualquer projeto é necessário:
-> Verificar build tool
-> Verificar se as dependencias existem
-> Verificar se o projeto possui application.yaml ou application.properties
Acredito que podemos abrir uma issue para tratar este ponto, e, deixar no radar né?

2022-10-10 14:40 UTC, vitorbg commented on stack.yaml
> +    content: docs/use-case.md
Boaaaa! Eu fiz o ajuste aqui e criei este arquivo na documentação. :)

2022-10-10 14:40 UTC, vitorbg commented on db-relational-plugin/snippets/postgresql/gradle-dependencies.txt
> +    testImplementation group: 'org.testcontainers', name: 'postgresql', version: '1.17.3'
Nesta primeira versão, estou considerando que o plugin será aplicado a projetos que foram criados pelo graphene.
Para evoluções do plugin e deixa-lo aplicavel em qualquer projeto é necessário:
-> Verificar build tool
-> Verificar se as dependencias existem
-> Verificar se o projeto possui application.yaml ou application.properties
Acredito que podemos abrir uma issue para tratar este ponto, e, deixar no radar né?

2022-11-20 03:51 UTC, closed without merging