update docker-compose version
stack-spot/graphene-java-api-stack pull request #16
Opened 2022-10-12 01:06 UTC by wesleyzup

Atualização da versão do arquivo docker-compose.yaml;
Ajuste no .gitginore do spring-web-api-template;
Ajuste no README;
Correção de erro de build ao escolher o gradle como ferramenta de build.

2022-10-13 13:31 UTC, lucas-almeida-zup requested changes
Por favor, verificar comentários para revisão

2022-10-13 13:31 UTC, lucas-almeida-zup commented on spring-web-api-template/readme/README-en.md
> +        docker compose up --build
Como mostra a execução de linha de comando, seria melhor deixar com o hífen

2022-10-13 13:31 UTC, lucas-almeida-zup commented on spring-web-api-template/readme/README-en.md
> +       docker compose down
Como mostra a execução de linha de comando, seria melhor deixar com o hífen

2022-10-13 13:31 UTC, lucas-almeida-zup commented on spring-web-api-template/buildtool/gradle/build.gradle
> +    runtimeOnly "io.micrometer:micrometer-registry-prometheus:${micrometerVersion}"
O padrão das outras dependências estão com aspas simples, seria legal deixar todos no mesmo padrão

2022-10-13 13:31 UTC, lucas-almeida-zup commented on spring-web-api-template/templates/README.md
> +         docker compose up --build
Como mostra a execução de linha de comando, seria melhor deixar com o hífen

2022-10-13 13:31 UTC, lucas-almeida-zup commented on spring-web-api-template/templates/README.md
> +        docker compose down
Como mostra a execução de linha de comando, seria melhor deixar com o hífen

2022-10-13 13:39 UTC, wesleyzup commented on spring-web-api-template/readme/README-en.md
> +        docker compose up --build
Acho válido usarmos essa verão mais nova, pois ela possibilita o uso de novas features, como health check por exemplo

2022-10-13 20:10 UTC, wesleyzup commented on spring-web-api-template/buildtool/gradle/build.gradle
> +    runtimeOnly "io.micrometer:micrometer-registry-prometheus:${micrometerVersion}"
Consegue me ajudar com esse ponto ?

2022-10-17 13:31 UTC, wesleyzup commented on spring-web-api-template/buildtool/gradle/build.gradle
> +    runtimeOnly "io.micrometer:micrometer-registry-prometheus:${micrometerVersion}"
Bom dia Lucas, resolvi o problema! Vê se consegue dar um olhada.
Valeu

2022-10-17 20:26 UTC, lucas-almeida-zup approved these changes
LGTM

2022-10-17 21:41 UTC, merged