review previous portuguese docs
stack-spot/graphene-java-api-stack pull request #17
Opened 2022-10-18 10:31 UTC by lucas-almeida-zup

- review previous portuguese docs  
- create english docs and set to default

2022-10-19 16:57 UTC, wesleyzup requested changes

2022-10-19 16:57 UTC, wesleyzup commented on metrics-plugin/docs/about.md
> +- **Audit**: O Spring Boot Actuator has a flexible framework of auditory that publish evens to an `AuditEventRepository`. This can be very useful to reports. For example, with the Spring Security, th
Verificar a parte em negrito

 **The** Spring Boot Actuator has a flexible framework of auditory that publish **events** to an `AuditEventRepository`. This can be very useful to reports. For example, with the Spring Security, the events of authentication will be published automatically.

2022-10-19 16:57 UTC, wesleyzup commented on metrics-plugin/docs/implementation.md
> +To know the options of configuration and use of the capacities added for this plugin, see the documentation of [Spring Boot Actuator](https://docs.spring.io/spring-boot/docs/current/reference/htmlsin
**Sugestão**
To know the options of configuration and **make** use of the capacities added for this plugin, see the documentation of [Spring Boot Actuator](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator).

2022-10-19 16:57 UTC, wesleyzup commented on metrics-plugin/docs/use-case.md
> +With this the Java application with Spring Boot and gradle/maven will have support to _metrics_
**Sugestão**
Adicionar virgula após **with this**

2022-10-19 16:57 UTC, wesleyzup commented on tracing-plugin/docs/about.md
> +## General Vision
Sugestão 
Substituir general vision para **Overview**

2022-10-19 16:57 UTC, wesleyzup commented on tracing-plugin/docs/about.md
> +### How the Tracing Plugin works
Se for uma pergunta, formular a frase utilizando o Does
How **does** the Tracing Plugin works

2022-10-19 16:57 UTC, wesleyzup commented on tracing-plugin/docs/usage.md
> +**Exemple output:**
Sugestão
**Output example**

2022-10-19 16:57 UTC, wesleyzup commented on logging-plugin/docs/use-case.md
> +This use case is ideal to initialize Java projects with Spring Boot and gradle or maven with _logging_ support.
**Sugestão**
This use case is ideal to initialize Java projects with Spring Boot and _logging_ support, being able to provide the options to choose Gradle or Maven as a build tool

2022-10-19 16:57 UTC, wesleyzup commented on metrics-plugin/docs/use-case.md
> +This use case is ideal to initialize Java projects with Spring Boot and gradle or maven with _metrics_ support.
**Sugestão**
This use case is ideal to initialize Java projects with Spring Boot and _metrics_ support, being able to provide the options to choose Gradle or Maven as a build tool

2022-10-19 16:57 UTC, wesleyzup commented on tracing-plugin/docs/use-case.md
> +This use case is ideal to initialize Java projects with Spring Boot and gradle or maven with _tracing_ support.
This use case is ideal to initialize Java projects with Spring Boot and _tracing_ support, being able to provide the options to choose Gradle or Maven as a build tool

2022-10-20 19:27 UTC, jessica-tw commented on logging-plugin/docs/usage.md
> +It's also need to install the itens below:
```suggestion
See below the items you need to have installed: 
```

2022-10-20 19:27 UTC, jessica-tw commented on logging-plugin/docs/usage.md
> +- [**StakSpot CLI**](https://docs.stackspot.com/v3.0.0/os-cli/installation/)
```suggestion
- [**STK CLI**](https://docs.stackspot.com/v3.0.0/os-cli/installation/)
```

2022-10-20 19:27 UTC, jessica-tw commented on logging-plugin/docs/use-case.md
> +It's possible to apply this plugin in an application of type APP, making use of StackSpot CLI, with the command:
```suggestion
It's possible to apply this plugin in the app-type application. Run the STK CLI command:
```

2022-10-20 19:27 UTC, jessica-tw commented on logging-plugin/docs/use-case.md
> +With this the Java application with Spring Boot and gradle/maven will have support to _logging_
```suggestion
This Java application with Spring Boot and Gradle/Maven will support _logging_.
```

2022-10-20 19:27 UTC, jessica-tw commented on logging-plugin/plugin.yaml
> +description: This plugin gives a pre configured structure logs in JSON format.
```suggestion
description: This plugin gives a pre-configured structure log in JSON format.
```

2022-10-20 19:27 UTC, jessica-tw commented on metrics-plugin/docs/about.md
> +- **Health**: Spring Boot Actuator enables endpoints to monitor and interact with your application, for example the endpoint `health` gives basic information of health check in your application.
```suggestion
This plugin adds the functionality to obtain metrics, enabling endpoints to monitor and publish auditory events in your application, using Spring Bott Actuator.
- **Health**: Spring Boot Actuator enables endpoints to monitor and interact with your application. For example, the  `health` endpoint gives basic information about the health check in your application.
```

2022-10-20 19:27 UTC, jessica-tw commented on metrics-plugin/docs/implementation.md
> +To know the options of configuration and use of the capacities added for this plugin, see the documentation of [Spring Boot Actuator](https://docs.spring.io/spring-boot/docs/current/reference/htmlsin
```suggestion
For more details about the configuration options and how to use the capacities added in this plugin, see the [Spring Boot Actuator](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator) documentation.

```

2022-10-20 19:27 UTC, jessica-tw commented on metrics-plugin/docs/usage.md
> +To use this plugin, it's need to have an application based on [Stack Web API com Spring](https://github.com/stack-spot/graphene-java-api-stack/tree/main/spring-web-api-template) and created with `Sta
```suggestion
- You need an application based on [Stack Web API com Spring](https://github.com/stack-spot/graphene-java-api-stack/tree/main/spring-web-api-template) and created with [**STK CLI**](https://stackspot.com/).

```

2022-10-20 19:27 UTC, jessica-tw commented on metrics-plugin/docs/usage.md
> +- [**StakSpot CLI**](https://docs.stackspot.com/v3.0.0/os-cli/installation/)
```suggestion
See below the items you need to have installed: 
- [**STK CLI**](https://docs.stackspot.com/v3.0.0/os-cli/installation/)
```

2022-10-20 19:27 UTC, jessica-tw commented on metrics-plugin/docs/use-case.md
> +With this the Java application with Spring Boot and gradle/maven will have support to _metrics_
```suggestion
This Java application with Spring Boot and Gradle/Maven will support _metrics_.
```

2022-10-20 19:27 UTC, jessica-tw commented on metrics-plugin/plugin.yaml
> +description: This plugin adds functionalities to obtain metrics of the application using Spring Actuator component.
```suggestion
description: This plugin adds functionalities to obtain the application's metrics using the Spring Actuator component.
```

2022-10-20 19:27 UTC, jessica-tw commented on spring-web-api-template/template.yaml
> +description: Template for Web APIs based on Java with Spring Boot and others Spring technologies.
```suggestion
description: Template for Web APIs based on Java with Spring Boot and other Spring technologies.
```

2022-10-20 19:27 UTC, jessica-tw commented on stack.yaml
> +description: Develop and publish Web APIs based on Stack Java for Cloud Native environments, with Spring Boot and other Spring technologies.
```suggestion
description: Develop and publish Web APIs based on Java Stack for Cloud Native environments with Spring Boot and other Spring technologies.
```

2022-10-20 19:27 UTC, jessica-tw commented on tracing-plugin/docs/about.md
> +### How the Tracing Plugin works
```suggestion
### How does the Tracing Plugin work?
```

2022-10-20 19:27 UTC, jessica-tw commented on tracing-plugin/docs/about.md
> +When applied, this plugin adds a class of configuration of _tracing_ making use of **`opentracing-spring-jaeger-web-starter`**.
```suggestion
This plugin adds a _tracing_ configuration class using **`opentracing-spring-jaeger-web-starter`**.
```

2022-10-20 19:27 UTC, jessica-tw commented on tracing-plugin/docs/about.md
> +When start the application, automatically, it connects and sends _tracing_ to an local endpoint.
```suggestion
When you start the application, it automatically connects and sends _tracing_ to a local endpoint.
```

2022-10-20 19:27 UTC, jessica-tw commented on tracing-plugin/docs/about.md
> +See more information about **jaeger** and how to deploy locally at [**jaegertracing**](https://www.jaegertracing.io/docs/1.37/deployment/)
```suggestion
For more information about **Jaeger** and how to deploy locally, see the [**jaegertracing**](https://www.jaegertracing.io/docs/1.37/deployment/) page.
```

2022-10-20 19:27 UTC, jessica-tw commented on tracing-plugin/docs/implementation.md
> +#### **Execution in Local Environment**
```suggestion
#### **Running on Local Environment**
```

2022-10-20 19:27 UTC, jessica-tw commented on tracing-plugin/docs/implementation.md
> +To use the plugin, run the command below to enable the container **`jaegertracing`**:
```suggestion
To use the plugin, run the command below to enable the **`jaegertracing`** container:
```

2022-10-20 19:27 UTC, jessica-tw commented on tracing-plugin/docs/implementation.md
> +To see the traces, access [this link](http://localhost:16686/).
```suggestion
To see the traces, access [this URL](http://localhost:16686/).
```

2022-10-20 19:27 UTC, jessica-tw commented on tracing-plugin/docs/implementation_pt-BR.md
> +O plugin também adicionar a dependência conforme *build_tool* selecionada:
```suggestion
O plugin também adiciona a dependência conforme *build_tool* selecionada:
```

2022-10-20 19:27 UTC, jessica-tw commented on tracing-plugin/docs/usage.md
> +### **Use**
```suggestion
### **Usage**
```

2022-10-20 19:27 UTC, jessica-tw commented on tracing-plugin/docs/usage.md
> +It's possible to apply this in an application of type APP with the StackSpot CLI. Run the command below to add the plugin in your application:
```suggestion
It's possible to apply this plugin in the app-type application. Run the STK CLI command to add the plugin to your application:
```

2022-10-20 19:27 UTC, jessica-tw commented on tracing-plugin/docs/usage.md
> +Execute the command below to import/update the local catalog which contain the Graphene Java API Stack
```suggestion
To import/update the local catalog with the Graphene Java API Stack, execute the command below:
```

2022-10-20 19:27 UTC, jessica-tw commented on tracing-plugin/docs/usage.md
> +To create an application and configure all plugins related to observability, copy and paste the command below in the terminal:
```suggestion
To create an application and configure all plugins related to observability, copy and paste the command below on your terminal:
```

2022-10-20 19:27 UTC, jessica-tw commented on tracing-plugin/docs/use-case.md
> +It's possible to apply this plugin in an application of type APP, making use of StackSpot CLI, with the command:
```suggestion
It's possible to apply this plugin in the app-type application. Run the STK CLI command:
```

2022-10-20 19:27 UTC, jessica-tw commented on tracing-plugin/docs/use-case.md
> +With this the Java application with Spring Boot and gradle/maven will have support to _tracing_
```suggestion
This Java application with Spring Boot and Gradle/Maven will support _tracing_
```

2022-10-20 19:27 UTC, jessica-tw commented on tracing-plugin/plugin.yaml
> +description: This plugin adds functionalities to trace of the application using Jaeger.
```suggestion
description: This plugin adds functionalities to trace the application using Jaeger.
```

2022-10-20 19:50 UTC, lucas-almeida-zup commented on tracing-plugin/docs/about.md
> +### How the Tracing Plugin works
Não é pergunta nesse caso

2022-10-20 19:54 UTC, lucas-almeida-zup commented on docs/about_pt-BR.md
> +- Clean Architecture
A ideia é sempre seguir 'Clean Architecture', não necessariamente que o template provisiona uma estrutura de códigos com diversas classes e pacotes por exemplo

2022-10-21 03:01 UTC, merged