Changes on db-relational plugin
stack-spot/graphene-java-api-stack pull request #19
Opened 2022-11-30 22:29 UTC by vitorbg

Changes on db-relational plugin:
  - Organizing the folders.
  - Adjusting the documentation for the Stackspot portal.

2022-12-01 20:04 UTC, wesleyzup commented on db-relational-plugin/plugin.yaml
> +display-name: Relational Plugin
Relational DB

2022-12-01 22:47 UTC, wesleyzup requested changes

2022-12-01 22:47 UTC, wesleyzup commented on db-relational-plugin/docs/use-case.md
> +This use case starts Java projects with Spring Boot and Maven/Gradle with relational database communication support.
This use case starts Java projects with Spring Boot using Maven or Gradle. It provides support to integrate relational databases, adding the corresponding dependence on the build tool according to the user's choice.
It also configures the appropriate connection driver and adds initial properties to the application.yaml. It configures the docker-compose, quickly enabling the connection between the application and the database.

2022-12-01 22:47 UTC, wesleyzup commented on db-relational-plugin/docs/use-case_pt-BR.md
> +Este caso de uso inicializa projetos Java com Spring Boot e Maven/Gradle com suporte a comunicação com banco de dados relacionais.
Este caso de uso inicia projetos Java com Spring Boot usando Maven ou Gradle. Ele fornece suporte para integrar bancos de dados relacionais, adicionando a dependência correspondente na ferramenta de construção de acordo com a escolha do usuário.
Ele também configura o driver de conexão apropriado e adiciona propriedades iniciais ao arquivo application.yaml. Também configura o docker-compose, permitindo realizar a conexão entre a aplicação e o banco de dados com o mínimo de esforço.

2022-12-01 22:47 UTC, wesleyzup commented on db-relational-plugin/docs/implementation.md
> +```
Adicionar a palavra **gradle**  após as crases para estilizar a estrutura conforme o padrão gradle
```
```gradle
```

2022-12-01 22:47 UTC, wesleyzup commented on db-relational-plugin/docs/implementation.md
> +```
Adicionar a palavra **gradle**  após as crases para estilizar a estrutura conforme o padrão gradle
```
```gradle
```

2022-12-01 22:47 UTC, wesleyzup commented on db-relational-plugin/docs/implementation_pt-BR.md
> +```
Adicionar a palavra **gradle**  após as crases para estilizar a estrutura conforme o padrão gradle
```
```gradle
```

2022-12-01 22:47 UTC, wesleyzup commented on db-relational-plugin/docs/implementation_pt-BR.md
> +```
Adicionar a palavra **gradle**  após as crases para estilizar a estrutura conforme o padrão gradle
```
```gradle
```

2022-12-06 00:05 UTC, vitorbg commented on db-relational-plugin/plugin.yaml
> +display-name: Relational Plugin
ok

2022-12-06 00:06 UTC, vitorbg commented on db-relational-plugin/docs/use-case.md
> +This use case starts Java projects with Spring Boot and Maven/Gradle with relational database communication support.
ok

2022-12-06 00:06 UTC, vitorbg commented on db-relational-plugin/docs/use-case_pt-BR.md
> +Este caso de uso inicializa projetos Java com Spring Boot e Maven/Gradle com suporte a comunicação com banco de dados relacionais.
ok

2022-12-06 00:07 UTC, vitorbg commented on db-relational-plugin/docs/implementation.md
> +```
ok

2022-12-06 00:07 UTC, vitorbg commented on db-relational-plugin/docs/implementation.md
> +```
ok

2022-12-06 00:08 UTC, vitorbg commented on db-relational-plugin/docs/implementation_pt-BR.md
> +```
ok

2022-12-06 00:08 UTC, vitorbg commented on db-relational-plugin/docs/implementation_pt-BR.md
> +```
ok

2022-12-06 12:22 UTC, wesleyzup approved these changes

2022-12-06 12:22 UTC, merged